# ---- Packages ----

library(bigsnpr)
library(bigstatsr)
library(dplyr)
library(readr)
library(yaml)
library(ggplot2)
library(adegenet)
library(statgenGWAS)
library(ade4)
library(terra)
library(geodata)
library(rnaturalearth)
library(rnaturalearthdata)
library(LEA)
library(reactable)
library(vegan)
library(pcadapt)
