---
title: "Analysis"
output: html_document
---

```{r setup, include=FALSE}
# Imports functions
function_files <- list.files("Functions", pattern = "\\.R$", full.names = TRUE)
invisible(lapply(sort(function_files), source))

# Imports config file
config <- read_yaml("config.yaml")

# Creates project directories
create_project_dirs(overwrite = config$run$overwrite)

# Sets status for pipeline modules
run_env <- isTRUE(config$analysis$run_env)
run_qc <- isTRUE(config$analysis$run_qc)
run_ld_pruning <- isTRUE(config$analysis$run_ld_pruning)
run_pca <- isTRUE(config$analysis$run_pca)
run_kinship <- isTRUE(config$analysis$run_kinship)
run_lmm <- isTRUE(config$analysis$run_lmm)
run_lfmm <- isTRUE(config$analysis$run_lfmm)
run_rda <- isTRUE(config$analysis$run_rda)
run_pcadapt <- isTRUE(config$analysis$run_pcadapt)
```

# Environmental Data Processing
## Extracting climatic variables
```{r, eval = run_env, include = run_env}
# Extracts climate variables
# if filtering by samples
if (config$subsetting$use) {
  # Reads metadata for subset
  metadata <- read.csv(config$subsetting$sample_metadata, stringsAsFactors = FALSE)
  # Extracts climatic variables for subset
  climate_data <- extract_climate_variables(
  metadata = metadata,
  lon_col = config$env$lon_col,
  lat_col = config$env$lat_col,
  sample_col = config$metadata$sample_col,
  var = config$env$var,
  res = config$env$res,
  climate_dir = config$env$path,
  output_file = config$env$output_file,
  overwrite = config$run$overwrite
  )
} else {
  metadata <- read.csv(config$metadata$file, stringsAsFactors = FALSE)
  climate_data <- extract_climate_variables(
  metadata = metadata,
  lon_col = config$env$lon_col,
  lat_col = config$env$lat_col,
  sample_col = config$metadata$sample_col,
  var = config$env$var,
  res = config$env$res,
  climate_dir = config$env$path,
  output_file = config$env$output_file,
  overwrite = config$run$overwrite
  )
}
```

## Climatic Data Distribution
### Geographic distribution
```{r, eval = run_env, include = run_env}
# Plots geographic distribution of selected climate variables
for (var in config$env$vars) {
  print(
    plot_climate_map(
      climate_data = climate_data,
      metadata = metadata,
      sample_col = config$metadata$sample_col,
      lon_col = config$env$lon_col,
      lat_col = config$env$lat_col,
      color_col = var
    )
  )
}
```

### Correlation
```{r, eval = run_env, include = run_env}
# Plots a correlation heatmap of climate variables
plot_climate_cor_heatmap(
  climate_data = climate_data
)
```

### Climate PCA
```{r, eval = run_env, include = run_env}
# Runs PCA of climate variables
climate_pca <- run_climate_pca(
  climate_data = climate_data,
  output_file = "Output/Structure/climate_pca.rds"
)

# Plots PCA
plot_climate_pca(climate_pca)
```
# Genotype Quality Control
```{r, eval = run_qc, include = run_qc}
qc_files <- paste0(config$qc_outputs$qc_prefix, c(".bed", ".bim", ".fam"))

# Filters genotype data to match samples with climatic variable data
keep_file <- create_keep_file(
  metadata = climate_data,
  fam_file = paste0(config$genotype$input_prefix, ".fam"),
  output_file = config$subsetting$keep_file,
  sample_col = config$metadata$sample_col
)

# if overwrite = FALSE and filtered files exist
if (!config$run$overwrite && all(file.exists(qc_files))) {
  message("Reusing filtered PLINK files: ", config$qc_outputs$qc_prefix)
  qc_prefix <- config$qc_outputs$qc_prefix
} else {
  # QC filters using PLINK
  qc_prefix <- plink_filter(
    input = config$genotype$input_prefix,
    output = config$qc_outputs$qc_prefix,
    plink = config$plink$path,
    keep = keep_file,
    geno_na = config$qc$geno_na,
    maf = config$qc$maf,
    ind_na = config$qc$ind_na
  )
}

# Extracts markers use_extract = TRUE
if (isTRUE(config$marker_subsetting$use_extract)) {
  qc_prefix <- plink_extract_markers(
    input = qc_prefix,
    output = config$marker_subsetting$output_prefix,
    plink = config$plink$path,
    extract_file = config$marker_subsetting$extract_file,
    overwrite = config$run$overwrite
  )
}

# Refilters metadata to match genotype data
metadata <- filter_metadata(
  metadata_file = config$metadata$file,
  fam_file = paste0(qc_prefix, ".fam"),
  sample_col = config$metadata$sample_col,
  output_file = config$metadata$filtered_file
)
```

```{r}
# In case QC module is not ran
if (!exists("qc_prefix")) {
  qc_prefix <- config$qc_outputs$qc_prefix
  qc_files <- paste0(qc_prefix, c(".bed", ".bim", ".fam"))
  # if files do not exist
  if (!all(file.exists(qc_files))) {
    message("QC was not run and QC files were not found. Using raw genotype prefix.")
    qc_prefix <- config$genotype$input_prefix
  } else {
    message("QC was not run. Reusing existing QC files: ", qc_prefix)
  }
}
```

# Population Structure & Kinship
## LD-pruning
```{r, eval = run_ld_pruning, include = run_ld_pruning}
ld_files <- paste0(config$qc_outputs$ld_prefix, c(".bed", ".bim", ".fam"))

# if overwrite = FALSE and ld_files exist
if (!config$run$overwrite && all(file.exists(ld_files))) {
  message("Reusing existing LD-pruned PLINK files: ", config$qc_outputs$ld_prefix)
  ld_prefix <- config$qc_outputs$ld_prefix
} else {
  # Filters genotype data with LD
  ld_prefix <- plink_ld_prune(
    input = qc_prefix,
    output = config$qc_outputs$ld_prefix,
    plink = config$plink$path,
    window = config$ld_pruning$window,
    step = config$ld_pruning$step,
    r2 = config$ld_pruning$r2
  )
}
```

## PCA
```{r, eval = run_pca, include = run_pca}
# Loading LD-pruned PLINK data as bigSNP object
ld_obj <- plink_to_bigSNP(
  bed_file = paste0(ld_prefix, ".bed"),
  overwrite = config$run$overwrite
)

# Runs PCA on genotype data
pca_result <- run_pca_bigsnpr(
  obj = ld_obj,
  n_pcs = config$pca$n_pcs,
  output_file = config$pca$output_file,
  covariates_file = config$pca$covariates_file,
  ncores = config$pca$ncores
)

# Plots PCA
pca_plot <- plot_pca(
  pca_result = pca_result,
  metadata = metadata,
  sample_col = config$metadata$sample_col,
  color_col = NULL,
  pc_x = 1,
  pc_y = 2
)

pca_plot
```
## Kinship
```{r}
# Creates GEMMA kinship matrix
gemma_kinship_file <- run_gemma_kinship(
  gemma = config$gemma$path,
  bfile = qc_prefix,
  output_prefix = config$gemma$kinship_prefix,
  output_dir = config$gemma$output_dir,
  overwrite = config$run$overwrite
)

# Calculates kinship statistics
kinship_stats <- summarize_gemma_kinship(gemma_kinship_file)
kinship_stats %>%
  mutate(value = round(value, 4)) %>%
  reactable()
```

# GEA
## LMM (GEMMA)
```{r, eval = run_lmm, include = run_lmm}
# Runs GEMMA
gemma_results <- run_gemma_lmm_all_variables(
  config = config,
  qc_prefix = qc_prefix,
  climate_data = climate_data,
  kinship_file = gemma_kinship_file,
  phenotypes = config$env$vars
)
```

### Results
```{r, eval = run_lmm, include = run_lmm}
gemma_results$evaluation %>%
  reactable()

gemma_results$best_by_variable %>%
  reactable()
```

### QQ Plots
```{r, eval = run_lmm, include = run_lmm}
for (pheno in gemma_results$best_by_variable$phenotype){
  print(
    plot_gemma_qq(
      results = gemma_results$results,
      phenotype = pheno
      )
  )
}
```

## LFMM
```{r, eval = run_lfmm, include = run_lfmm}
# Creates genotype matrix for LMM
qc_obj <- plink_to_bigSNP(
  bed_file = paste0(qc_prefix, ".bed"),
  overwrite = config$run$overwrite
)

G_qc <- qc_obj$genotypes
map_qc <- qc_obj$map
fam_qc <- qc_obj$fam

# Runs LFMM
lfmm_results <- run_lfmm_all_variables(
  config = config,
  geno = G_qc,
  map = map_qc,
  fam = fam_qc,
  climate_data = climate_data,
  phenotypes = config$env$vars
)
```

### Results
```{r, eval = run_lfmm, include = run_lfmm}
lfmm_results$evaluation %>%
  reactable()

lfmm_results$best_by_variable %>%
  reactable()
```

### QQ Plots
```{r, eval = run_lfmm, include = run_lfmm}
for (pheno in lfmm_results$best_by_variable$phenotype) {
  print(
    plot_lfmm_qq(
      results = lfmm_results$results,
      phenotype = pheno
    )
  )
}
```

## RDA
```{r, eval = run_rda, include = run_rda}
# Creates genotype matrix for RDA
qc_obj <- plink_to_bigSNP(
  bed_file = paste0(qc_prefix, ".bed"),
  overwrite = config$run$overwrite
)

G_qc <- qc_obj$genotypes
map_qc <- qc_obj$map
fam_qc <- qc_obj$fam

# Runs RDA
rda_results <- run_rda_all_variables(
  config = config,
  geno = G_qc,
  map = map_qc,
  fam = fam_qc,
  climate_data = climate_data,
  phenotypes = config$env$vars
)
```

### Results
```{r, eval = run_rda, include = run_rda}
rda_results$evaluation %>%
  reactable()

rda_results$best_by_variable %>%
  reactable()
```

### QQ Plots
```{r}
for (pheno in rda_results$best_by_variable$phenotype) {
  print(
    plot_rda_qq(
      results = rda_results$results,
      phenotype = pheno
    )
  )
}
```

## pcadapt
```{r, eval = run_pcadapt, include = run_pcadapt}
# Runs pcadapt
pcadapt_results <- run_pcadapt_strategies(
  config = config,
  qc_prefix = qc_prefix
)
```

### Results
```{r, eval = run_pcadapt, include = run_pcadapt}
pcadapt_results$evaluation %>%
  reactable()

pcadapt_results$best_evaluation %>%
  reactable()
```

### QQ Plot
```{r}
plot_pcadapt_qq(
  results = pcadapt_results$results
)
```

